# Generated by Django 4.2 on 2023-04-08 18:05

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(null=True, upload_to='images')),
                ('first_name', models.CharField(db_index=True, max_length=250)),
                ('last_name', models.CharField(db_index=True, max_length=250)),
                ('email', models.EmailField(max_length=250, unique=True)),
                ('birthdate', models.DateField(help_text='Add Birthdate')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(default='+91', max_length=128, region=None)),
                ('address', models.CharField(max_length=250)),
            ],
        ),
    ]
